### ISSUE TITLE
Can this also install mods to the client?

### ISSUE THREAD

**Issue by nodingneu** [nothub/mrpack-install#15]
I noticed this tool creates a server folder and installs mods for the server. If I just copy the generated `mods` folder to my local game's Minecraft folder, will my local game have all the mods from the modpack?

**Comment by nothub** [comment]
No, this will not work in most cases. In Minecraft modpacks, the files for the client and server side are usually split up. Modpacks in the mrpack format also contain "override" files, which can include files outside of the `mods` folder and which also can be different for the client and server side.
However, unpacking the modpack files for the client side could be added as a new feature to mrpack-install in the future.
