### ISSUE TITLE
Automatically filter client-side mods

### ISSUE THREAD

**Issue by VELD-Dev** [nothub/mrpack-install#34]
In order not to have client-side mods, such as Embeddium, Rubidium, JEI, REI, etc...
Mods have a data on the Modrinth API that tells if the mod is client-side, server-side or both

**Comment by nothub** [comment]
Is there a specific problem you want to report? When setting up a server, mrpack-install downloads all mods where `env` `server` is not `unsupported` in the mrpack specification of the modpack.

**Comment by VELD-Dev** [comment]
Well actually it seems to not recognize when an env is a server or not, how do you tell the app that it is a server or not since the server arg does not take any mod pack link or so ?

**Comment by nothub** [comment]
The env is always a server env because the tool is for installing modpack-servers.

**Comment by nothub** [comment]
No reply from ticket author, closing.
