### ISSUE TITLE
"File path is not safe"

### ISSUE THREAD

**Issue by zhongjiedong** [nothub/mrpack-install#49]
[v0.17.2-beta](https://github.com/nothub/mrpack-install/releases/tag/v0.17.2-beta)

`c:\MCServers>mrpack-install "c:\MCServers\mrpacks\Prominence II [RPG] 2.8.4.mrpack"
Installing "Prominence II [RPG]" from "c:\\MCServers\\mrpacks\\Prominence II [RPG] 2.8.4.mrpack" to "c:\\MCServers\\mc"
File path is not safe: c:\MCServers\mc\mods\do-a-barrel-roll-3.3.7+1.20-fabric.jar`

Nothing is created at all so it seems to be failing in the first step

**Comment by zhongjiedong** [comment]
something to do with the double  \\ ?

**Comment by nothub** [comment]
I just tried to reproduce the issue but I am unable to recreate the problem.

![image](https://github.com/nothub/mrpack-install/assets/48992448/7898a785-67c7-4d94-9c84-59f490a36554)

I tested both, the current stable (`v0.16.10`) and the latest beta (`v0.17.2`).

The commands i executed were:
`mrpack-install-0.16.10.exe "C:\Users\Hub\MCServers\mrpacks\Prominence II [RPG] 2.8.4.mrpack"`
and
`mrpack-install-0.17.2-beta.exe "C:\Users\Hub\MCServers\mrpacks\Prominence II [RPG] 2.8.4.mrpack"`

Is the `mrpack` file you use the unchanged original from modrinth?

**Comment by zhongjiedong** [comment]
yep I downloaded from modrinth, specifically the prominence II pack. Can you try and let me know if it works?

**Comment by nothub** [comment]
> Can you try and let me know if it works?

I tried again and I found the issue.

Windows seems to ignore the case of the drive, e.g. `c:\MCServers` and `C:\MCServers` point to the same location.
This causes a bug somewhere in the path validation.

For now, make sure your working directory is `C:\MCServers` and not `c:\MCServers` to circumvent the problem.

I gonna test a few ways to approach this issue.

![image](https://github.com/nothub/mrpack-install/assets/48992448/1652c855-2f11-479b-9777-a5cba4364aa8)

**Comment by nothub** [comment]
I created a new release [v0.17.3-beta](https://github.com/nothub/mrpack-install/releases/tag/v0.17.3-beta) which solves the problem for me. @zhongjiedong can you verify that the new version also fixes the problem on your side?

**Comment by zhongjiedong** [comment]
Fixed the issue, thanks so much!

**Comment by nothub** [comment]
Awesome :smiley: Thank you for reporting the issue!
