### ISSUE TITLE
How can i export only server or client-server mods

### ISSUE THREAD

**Issue by Seva44** [nothub/mrpack-install#55]
i tried to export [Create-Extra ](https://modrinth.com/modpack/create-extra) modpack, using `mrpack-install create.mrpack --server-dir servers/create`. When i do it in saw client-side mods like `blur+` and `sodium`

**Comment by nothub** [comment]
I just downloaded the `Create Extra (Fabric) 1.5.6.mrpack` file for the modpack to analyze the issue.

The modpack authors decided to set the flags to require e.g. the Sodium mod on both sides, client and server.

This is a bug on their side, not in this project.

Example snippet from the `modrinth.index.json` in question:

```
    {
      "path": "mods/sodium-extra-0.5.4+mc1.20.1-build.115.jar",
      "hashes": {
        "sha1": "890864a6ab5d77d57d8d757bcc31f5379b5a11b1",
        "sha512": "ab561186421776d0db506dcbf1a724f80b345be5769ff00aa4327161c79af6e3f353eb65345ce06da30546ffa6b43e1c4a4c41dd246b7e473b131fd727997a85"
      },
      "env": {
        "client": "required",
        "server": "required"
      },
      "downloads": [
        "https://cdn.modrinth.com/data/PtjYWJkn/versions/I7ggF6B5/sodium-extra-0.5.4%2Bmc1.20.1-build.115.jar"
      ],
      "fileSize": 385539
    },
    ```
